name: autotests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  data_test:
    runs-on: ubuntu-latest
    container: python:3.12

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup tests deps
        run: |
          pip install pytest pandas

      - name: Run tests
        run: |
          pytest -v tests
